# Generated by Django 3.2.13 on 2022-09-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20220930_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='Review', max_length=80),
        ),
    ]
